# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll Site to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: ["main"]

  # Allow manual triggering of the workflow from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  # Ensures only one deployment runs at a time
  group: "github-pages-deployment"
  cancel-in-progress: false

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify the Ruby version compatible with your Jekyll site
          cache-bundle: true  # Enables caching for Ruby gems

      - name: Install Dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build -d ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          # The artifact uploaded in the build job
          artifacts: _site


